import {keepPreviousData, useMutation, useQuery, useQueryClient} from "@tanstack/react-query";
import {useNavigate} from "@tanstack/react-router";
import type {SortingState} from "@tanstack/react-table";
import {AlertTriangle, CheckCircle2, Download, Filter, History, Plus, RefreshCw, RotateCcw, Search, ShieldAlert, Wrench} from "lucide-react";
import {useEffect, useMemo, useState, type ReactNode} from "react";
import {toast} from "sonner";
import {Button, Card, CardContent, Input, Select} from "@/src/components/ui";
import {ErpColumnVisibilityMenu, DashboardSection, ErpDataTable, ErpDetailDrawer, ErpFilterBar, ErpLoadingState, ErpPageError, ErpPageHeader, ErpStatusBadge, ErpWarehousePageFrame, MetricsRegion, type QuickStatusItemData} from "@/src/components/common";
import {ApiError, aftersalesApi, queryKeys, type AuthSession} from "@/src/services/api";
import {createCapabilities, useAuth} from "@/src/app/auth";
import {useTablePreferences} from "@/src/hooks/useTablePreferences";
import {useUrlSearchState} from "@/src/hooks/useUrlSearchState";
import {formatCurrency} from "@/src/lib/format";
import {aftersalesStatuses, aftersalesTypes, type AftersalesCreateFormValues, type AftersalesFilters, type AftersalesListItem, type AftersalesResolutionFormValues, type AftersalesWorkspaceSnapshot} from "@/src/types/aftersales";
import {AftersalesCreateDialog} from "../components/AftersalesCreateDialog";
import {AftersalesResolutionDialog} from "../components/AftersalesResolutionDialog";
import {createAftersalesColumns, formatDateTime, statusTone} from "../aftersales.columns";
import {aftersalesFiltersToSearch, defaultAftersalesFilters, filterAftersales, parseAftersalesFilters, sortAftersales} from "../aftersales.filters";

function useUrlState() {return useUrlSearchState({defaultValue: defaultAftersalesFilters, parse: parseAftersalesFilters, serialize: aftersalesFiltersToSearch});}

export function AftersalesWorkspacePage() {
  const {session, logout} = useAuth(); const {value: filters, commit} = useUrlState(); const allowed = createCapabilities(session).menu("aftersales");
  const workspaceQuery = useQuery({queryKey: queryKeys.aftersales.workspace(session?.user.id || "anonymous"), queryFn: ({signal}) => aftersalesApi.workspace(signal), enabled: Boolean(session && allowed), placeholderData: keepPreviousData, retry: false});
  if (!session) return <Card><ErpLoadingState title="正在验证售后维护权限" /></Card>;
  if (!allowed) return <ErpPageError title="当前账号没有售后维护权限" description="服务器权限未包含 aftersales 菜单，请联系管理员授权。" />;
  return <AftersalesContent session={session} snapshot={workspaceQuery.data} pending={workspaceQuery.isPending} fetching={workspaceQuery.isFetching} error={workspaceQuery.error as Error | null} filters={filters} onFiltersChange={commit} onRetry={() => void workspaceQuery.refetch()} onAuthExpired={logout} />;
}

function AftersalesContent({session, snapshot, pending, fetching, error, filters, onFiltersChange, onRetry, onAuthExpired}: {session: AuthSession; snapshot?: AftersalesWorkspaceSnapshot; pending: boolean; fetching: boolean; error: Error | null; filters: AftersalesFilters; onFiltersChange: (filters: AftersalesFilters) => void; onRetry: () => void; onAuthExpired: () => void}) {
  const navigate = useNavigate(); const queryClient = useQueryClient(); const [sorting, setSorting] = useState<SortingState>([]); const {columnVisibility, setColumnVisibility, density, setDensity} = useTablePreferences<Record<string, boolean>>({feature: "aftersales", userId: session.user.id, defaultVisibility: {}, defaultDensity: "compact"}); const [detail, setDetail] = useState<AftersalesListItem | null>(null); const [createOpen, setCreateOpen] = useState(false); const [resolving, setResolving] = useState<AftersalesListItem | null>(null);
  const items = snapshot?.items || []; const candidates = snapshot?.candidates || [];
  const filtered = useMemo(() => sortAftersales(filterAftersales(items, filters), sorting), [filters, items, sorting]); const totalPages = Math.max(1, Math.ceil(filtered.length / filters.pageSize)); useEffect(() => {if (filters.page > totalPages) onFiltersChange({...filters, page: totalPages});}, [filters, onFiltersChange, totalPages]); const pageRows = filtered.slice((filters.page - 1) * filters.pageSize, filters.page * filters.pageSize);
  const goToReturns = () => {void navigate({to: "/sales/returns/new"});};
  const invalidate = async () => {await Promise.all([queryClient.invalidateQueries({queryKey: queryKeys.aftersales.all()}), queryClient.invalidateQueries({queryKey: queryKeys.state.all()}), queryClient.invalidateQueries({queryKey: queryKeys.inventory.all()}), queryClient.invalidateQueries({queryKey: queryKeys.sales.all()}), queryClient.invalidateQueries({queryKey: queryKeys.customers.all()})]);};
  const handleError = (caught: Error) => {if (caught instanceof ApiError && caught.isUnauthorized) {onAuthExpired(); return;} toast.error(caught.message);};
  const createMutation = useMutation({mutationFn: async (values: AftersalesCreateFormValues) => {const candidate = candidates.find((item) => item.inventoryId === values.candidateId); if (!candidate) throw new Error("所选库存卡已不存在，请刷新后重试"); if (candidate.activeClaimId) throw new Error(`该 SN 已存在处理中工单 ${candidate.activeClaimId}`); return aftersalesApi.create(values, candidate, session.user.displayName);}, onSuccess: async (created) => {toast.success("售后工单已登记，库存卡已进入售后中"); setCreateOpen(false); setDetail(created); await invalidate();}, onError: handleError});
  const resolveMutation = useMutation({mutationFn: async ({record, values}: {record: AftersalesListItem; values: AftersalesResolutionFormValues}) => aftersalesApi.resolve(record.id, values, session.user.displayName), onSuccess: async (updated) => {toast.success(updated.status === "已拒绝" ? "售后工单已拒绝" : "售后工单已结案"); setResolving(null); setDetail(updated); await invalidate();}, onError: handleError});
  const columns = useMemo(() => createAftersalesColumns({onOpen: setDetail, onReturn: goToReturns}), []);
  const activeCount = items.filter((item) => ["待处理", "检测中"].includes(item.status)).length; const completeCount = items.filter((item) => item.status === "已完成").length; const repairCost = items.reduce((sum, item) => sum + item.repairCost, 0); const activeFilters = Number(Boolean(filters.keyword)) + Number(filters.status !== "all") + Number(filters.type !== "all");
  const quickStatus: QuickStatusItemData[] = [{icon: <ShieldAlert className="h-4 w-4" />, label: "待处理", value: `${activeCount} 件`, description: "待处理与检测中", tone: activeCount ? "warning" : "success"}, {icon: <Wrench className="h-4 w-4" />, label: "可登记 SN", value: `${candidates.filter((item) => !item.activeClaimId).length} 张`, description: "已售且已关联销售单", tone: "info"}];
  const exportRows = () => {const rows = [["售后编号", "销售单号", "客户", "联系方式", "商品", "SN", "类型", "状态", "客户反馈", "维修支出", "退款金额", "结论", "经办人", "登记时间"], ...filtered.map((item) => [item.id, item.salesInvoiceNo, item.customerName, item.contact, item.productName, item.serialNumber, item.type, item.status, item.description, item.repairCost, item.refundAmount, item.finalResult, item.handler || "", item.createdAt])]; const url = URL.createObjectURL(new Blob([`\uFEFF${rows.map((row) => row.map(csvCell).join(",")).join("\n")}`], {type: "text/csv;charset=utf-8"})); const link = document.createElement("a"); link.href = url; link.download = "售后工单.csv"; link.click(); URL.revokeObjectURL(url);};
  return <ErpWarehousePageFrame><ErpPageHeader title="售后维护" subtitle="按已售 SN 登记并追踪维修、检测争议、换货与补差价；退货退款统一走销售退货。" quickStatus={quickStatus} actions={<><Button type="button" size="sm" variant="secondary" onClick={goToReturns}>办理销售退货</Button><Button type="button" size="sm" variant="secondary" onClick={onRetry} disabled={fetching}><RefreshCw className={`h-4 w-4 ${fetching ? "animate-spin" : ""}`} />刷新</Button><Button type="button" size="sm" variant="primary" onClick={() => {createMutation.reset(); setCreateOpen(true);}}><Plus className="h-4 w-4" />登记售后</Button></>} />
    <MetricsRegion><MetricCard label="售后工单" value={`${items.length} 件`} detail="当前账号可见整库" icon={<History className="h-4 w-4" />} /><MetricCard label="待处理 / 检测中" value={`${activeCount} 件`} detail="需要继续跟进" icon={<AlertTriangle className="h-4 w-4" />} tone={activeCount ? "warning" : "success"} /><MetricCard label="已完成" value={`${completeCount} 件`} detail="已记录处理结论" icon={<CheckCircle2 className="h-4 w-4" />} tone="success" /><MetricCard label="累计维修支出" value={formatCurrency(repairCost)} detail="结案记录中的维修费用" icon={<Wrench className="h-4 w-4" />} tone={repairCost ? "warning" : "neutral"} /></MetricsRegion>
    <ErpFilterBar actions={<><Button type="button" size="sm" variant="ghost" onClick={() => onFiltersChange(defaultAftersalesFilters)}><RotateCcw className="h-4 w-4" />重置</Button><Button type="button" size="sm" variant="secondary" onClick={exportRows}><Download className="h-4 w-4" />导出</Button></>}><div className="relative min-w-64 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--erp-color-text-muted)]" /><Input className="pl-9" value={filters.keyword} onChange={(event) => onFiltersChange({...filters, keyword: event.target.value, page: 1})} placeholder="工单、销售单、客户、SN、型号或问题描述" aria-label="搜索售后工单" /></div><Select className="w-36" value={filters.status} onValueChange={(status) => onFiltersChange({...filters, status: status as AftersalesFilters["status"], page: 1})} options={[{value: "all", label: "全部状态"}, ...aftersalesStatuses.map((value) => ({value, label: value}))]} aria-label="售后状态" /><Select className="w-36" value={filters.type} onValueChange={(type) => onFiltersChange({...filters, type: type as AftersalesFilters["type"], page: 1})} options={[{value: "all", label: "全部类型"}, ...aftersalesTypes.map((value) => ({value, label: value}))]} aria-label="售后类型" /></ErpFilterBar>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs text-[var(--erp-color-text-muted)]"><Filter className="h-3.5 w-3.5" /><ErpStatusBadge label={activeFilters ? `${activeFilters} 项筛选` : "全部工单"} tone={activeFilters ? "info" : "neutral"} /><span>筛选、排序和分页仅作用于已加载售后集合。</span></div><div className="flex items-center gap-2"><ErpColumnVisibilityMenu columns={columns} visibility={columnVisibility} onVisibilityChange={setColumnVisibility} /><div className="inline-flex rounded-[var(--erp-radius-md)] border border-[var(--erp-color-border)] bg-[var(--erp-color-surface)] p-0.5"><Button type="button" size="sm" variant={density === "comfortable" ? "secondary" : "ghost"} onClick={() => setDensity("comfortable")}>舒适</Button><Button type="button" size="sm" variant={density === "compact" ? "secondary" : "ghost"} onClick={() => setDensity("compact")}>紧凑</Button></div></div></div>
    <DashboardSection title="售后工单流水" description="点击行查看完整反馈、处理结论和费用；历史退货工单只读并引导到销售退货。" actions={<ErpStatusBadge label={`已加载 ${items.length} 条`} tone="info" />}><ErpDataTable columns={columns} data={pageRows} getRowId={(row) => row.id} loading={pending} fetching={fetching} error={error} errorTitle="售后工单加载失败" emptyTitle="暂无匹配售后工单" emptyDescription={activeFilters ? "请调整搜索或筛选条件。" : "点击登记售后创建第一张工单。"} onRetry={onRetry} onRowClick={setDetail} manualSorting sorting={sorting} onSortingChange={setSorting} page={filters.page} pageSize={filters.pageSize} total={filtered.length} onPageChange={(page) => onFiltersChange({...filters, page})} onPageSizeChange={(pageSize) => onFiltersChange({...filters, page: 1, pageSize})} columnVisibility={columnVisibility} onColumnVisibilityChange={setColumnVisibility} enableColumnResizing density={density} stickyHeader /></DashboardSection>
    <AftersalesDetailDrawer record={detail} onClose={() => setDetail(null)} onResolve={() => {if (detail) {resolveMutation.reset(); setResolving(detail);}}} onReturn={goToReturns} />
    <AftersalesCreateDialog open={createOpen} candidates={candidates} pending={createMutation.isPending} error={createMutation.error instanceof Error ? createMutation.error.message : undefined} onOpenChange={setCreateOpen} onSubmit={async (values) => {await createMutation.mutateAsync(values);}} />
    <AftersalesResolutionDialog record={resolving} pending={resolveMutation.isPending} error={resolveMutation.error instanceof Error ? resolveMutation.error.message : undefined} onClose={() => setResolving(null)} onSubmit={async (values) => {if (resolving) await resolveMutation.mutateAsync({record: resolving, values});}} />
  </ErpWarehousePageFrame>;
}

function AftersalesDetailDrawer({record, onClose, onResolve, onReturn}: {record: AftersalesListItem | null; onClose: () => void; onResolve: () => void; onReturn: () => void}) {const active = record && ["待处理", "检测中"].includes(record.status); return <ErpDetailDrawer open={Boolean(record)} onOpenChange={(open) => {if (!open) onClose();}} title={record?.id || "售后工单"} description={record ? `${record.salesInvoiceNo} · ${formatDateTime(record.createdAt)}` : undefined} footer={record ? record.historicalReturn ? <Button className="w-full" variant="primary" onClick={onReturn}>前往销售退货</Button> : active ? <Button className="w-full" variant="primary" onClick={onResolve}>处理并结案</Button> : undefined : undefined}><div className="space-y-5">{record && <><div className="flex flex-wrap gap-2"><ErpStatusBadge label={record.status} tone={statusTone(record.status)} /><ErpStatusBadge label={record.type} tone={record.historicalReturn ? "warning" : "neutral"} /></div><div className="grid grid-cols-2 gap-3"><Fact label="客户" value={record.customerName} /><Fact label="联系方式" value={record.contact || "未记录"} /><Fact label="商品" value={record.model || record.productName} /><Fact label="SN" value={record.serialNumber || "未记录"} /><Fact label="库存编号" value={record.inventoryNo || "未记录"} /><Fact label="经办人" value={record.handler || "未记录"} /><Fact label="维修支出" value={formatCurrency(record.repairCost)} /><Fact label="退款记录" value={formatCurrency(record.refundAmount)} /></div><DashboardSection title="客户反馈"><p className="whitespace-pre-wrap text-sm leading-relaxed text-[var(--erp-color-text-secondary)]">{record.description || "未记录"}</p></DashboardSection>{record.finalResult && <DashboardSection title="处理结论"><p className="whitespace-pre-wrap text-sm leading-relaxed text-[var(--erp-color-text-secondary)]">{record.finalResult}</p></DashboardSection>}{record.historicalReturn && <div className="rounded-[var(--erp-radius-lg)] bg-[var(--erp-color-warning-soft)] p-4 text-sm leading-relaxed text-[var(--erp-color-warning)]">这是历史售后退货记录。新退货必须在销售退货中关联原销售单处理，此处不直接结案或退款。</div>}</>}</div></ErpDetailDrawer>;}

function MetricCard({label, value, detail, icon, tone = "neutral"}: {label: string; value: string; detail: string; icon: ReactNode; tone?: "neutral" | "info" | "success" | "warning"}) {return <Card><CardContent className="flex items-start justify-between gap-3 p-4"><div><p className="text-xs font-semibold text-[var(--erp-color-text-secondary)]">{label}</p><p className="mt-2 font-mono text-xl font-bold">{value}</p><p className="mt-1 text-[11px] text-[var(--erp-color-text-muted)]">{detail}</p></div><ErpStatusBadge label={icon} tone={tone} /></CardContent></Card>;}
function Fact({label, value}: {label: string; value: string}) {return <div className="rounded-[var(--erp-radius-md)] bg-[var(--erp-color-surface-muted)] p-3"><p className="text-xs text-[var(--erp-color-text-muted)]">{label}</p><p className="mt-1 break-words text-sm font-semibold">{value}</p></div>;}
function csvCell(value: string | number) {const text = String(value); return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;}
