import {Button, Textarea} from "@/src/components/ui";
import {ErpDialogShell, ErpStatusBadge} from "@/src/components/common";
import {MAX_QUOTE_PASTE_ROWS, parseMarketQuotePaste, type QuotePasteResult} from "../quote.import";

export function MarketQuotePasteDialog({open, value, pending, onValueChange, onOpenChange, onImport}: {open: boolean; value: string; pending: boolean; onValueChange: (value: string) => void; onOpenChange: (open: boolean) => void; onImport: (result: QuotePasteResult) => void}) {
  const result = parseMarketQuotePaste(value);
  return <ErpDialogShell open={open} onOpenChange={onOpenChange} pending={pending} size="lg" title="批量粘贴行情" description={`支持 Excel Tab 和逗号分隔；单次最多 ${MAX_QUOTE_PASTE_ROWS} 行。导入由现有服务端按品牌与型号新增或更新。`} footer={<><Button type="button" variant="secondary" onClick={() => onOpenChange(false)} disabled={pending}>取消</Button><Button type="button" variant="primary" onClick={() => onImport(result)} disabled={pending || !result.rows.length}>{pending ? "导入中…" : `导入 ${result.rows.length} 行`}</Button></>}>
    <div className="space-y-4"><div className="rounded-[var(--erp-radius-md)] bg-[var(--erp-color-info-soft)] p-3 erp-data-number text-xs leading-6 text-[var(--erp-color-text-secondary)]">简写：型号, 回收价, 销售价, 走势, 说明<br />完整：型号, 品牌, 回收价, 销售价, 走势, 说明</div><Textarea className="min-h-52" value={value} onChange={(event) => onValueChange(event.target.value)} disabled={pending} placeholder="RTX 4090, NVIDIA, 18000, 19500, 平稳, 正常收售" /><div className="flex flex-wrap gap-2"><ErpStatusBadge label={`有效 ${result.rows.length} 行`} tone={result.rows.length ? "success" : "neutral"} />{result.errors.length > 0 && <ErpStatusBadge label={`错误 ${result.errors.length} 行`} tone="danger" />}</div>{result.errors.length > 0 && <div className="max-h-28 overflow-y-auto rounded-[var(--erp-radius-md)] bg-[var(--erp-color-danger-soft)] p-3 text-xs text-[var(--erp-color-danger)]">{result.errors.slice(0, 8).map((error) => <p key={error}>{error}</p>)}</div>}</div>
  </ErpDialogShell>;
}
