import {zodResolver} from "@hookform/resolvers/zod";
import {Controller, useForm} from "react-hook-form";
import {useEffect} from "react";
import {Button, Dialog, Input, Select, Textarea} from "@/src/components/ui";
import {ErpAmountInput, ErpFormSection, ErpPageError} from "@/src/components/common";
import type {MarketQuoteFormValues, MarketQuoteItem} from "@/src/types/quote";
import {defaultMarketQuoteValues, marketQuoteSchema} from "../quote.schema";

export function MarketQuoteDialog({open, quote, pending, error, onOpenChange, onSubmit}: {open: boolean; quote: MarketQuoteItem | null; pending: boolean; error?: string; onOpenChange: (open: boolean) => void; onSubmit: (values: MarketQuoteFormValues) => Promise<void>}) {
  const form = useForm<MarketQuoteFormValues>({resolver: zodResolver(marketQuoteSchema), defaultValues: defaultMarketQuoteValues});
  useEffect(() => {
    form.reset(quote ? {model: quote.model, brand: quote.brand, buyPrice: quote.buyPrice || 0, sellPrice: quote.sellPrice || 0, trend: quote.trend, note: quote.note || ""} : defaultMarketQuoteValues);
  }, [form, open, quote]);
  const fieldError = (name: keyof MarketQuoteFormValues) => form.formState.errors[name]?.message;
  return <Dialog.Root open={open} onOpenChange={(next) => {if (!pending) onOpenChange(next);}}><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 erp-modal-layer bg-[var(--erp-color-backdrop)]" /><Dialog.Viewport className="fixed inset-0 erp-modal-layer flex items-center justify-center p-4"><Dialog.Popup className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[var(--erp-radius-xl)] border border-[var(--erp-color-border)] bg-[var(--erp-color-surface)] shadow-[var(--erp-shadow-popover)]"><form onSubmit={form.handleSubmit(onSubmit)}><div className="border-b border-[var(--erp-color-border)] p-5"><Dialog.Title className="text-lg font-bold">{quote ? "更新行情价格" : "新增行情参考"}</Dialog.Title><Dialog.Description className="mt-1 text-sm text-[var(--erp-color-text-secondary)]">更新时由服务端记录真实历史点，并同步关联在库商品价格。</Dialog.Description></div><div className="space-y-4 p-5">{error && <ErpPageError title="保存失败" description={error} />}<ErpFormSection title="行情信息" description={quote ? "型号与品牌沿用原记录，避免改变关联关系。" : "录入当前可执行的回收与销售参考价。"}><div className="grid gap-4 sm:grid-cols-2"><Field label="商品型号" error={fieldError("model")}><Input {...form.register("model")} disabled={pending || Boolean(quote)} placeholder="例如 RTX 4090" /></Field><Field label="品牌" error={fieldError("brand")}><Input {...form.register("brand")} disabled={pending || Boolean(quote)} placeholder="例如 NVIDIA" /></Field><Field label="回收参考价" error={fieldError("buyPrice")}><Controller control={form.control} name="buyPrice" render={({field}) => <ErpAmountInput value={field.value} onBlur={field.onBlur} onValueChange={(value) => field.onChange(value.floatValue || 0)} disabled={pending} />} /></Field><Field label="销售参考价" error={fieldError("sellPrice")}><Controller control={form.control} name="sellPrice" render={({field}) => <ErpAmountInput value={field.value} onBlur={field.onBlur} onValueChange={(value) => field.onChange(value.floatValue || 0)} disabled={pending} />} /></Field><Field label="走势" error={fieldError("trend")}><Controller control={form.control} name="trend" render={({field}) => <Select value={field.value} onValueChange={field.onChange} options={[{value: "stable", label: "价格平稳"}, {value: "up", label: "参考价上调"}, {value: "down", label: "参考价下调"}]} disabled={pending} />} /></Field><Field label="波动说明" error={fieldError("note")} className="sm:col-span-2"><Textarea {...form.register("note")} disabled={pending} placeholder="说明近期价格变化和报价注意事项" /></Field></div></ErpFormSection></div><div className="flex justify-end gap-2 border-t border-[var(--erp-color-border)] p-5"><Button type="button" variant="secondary" onClick={() => onOpenChange(false)} disabled={pending}>取消</Button><Button type="submit" variant="primary" disabled={pending}>{pending ? "保存中…" : quote ? "保存更新" : "创建行情"}</Button></div></form></Dialog.Popup></Dialog.Viewport></Dialog.Portal></Dialog.Root>;
}

function Field({label, className, children}: {label: string; error?: string; className?: string; children: React.ReactNode}) {
  return <label className={className}><span className="mb-2 block text-sm font-semibold">{label}</span>{children}</label>;
}
