import {StateCollectionPage, type StateCollectionPageProps} from "./StateCollectionPage";

const configs = {
  users: {menuId: "permissions", title: "员工权限", subtitle: "查看成员、角色、账号状态和最近登录。", collection: "systemUsers", columns: [{key: "displayName", label: "成员"}, {key: "username", label: "账号"}, {key: "role", label: "角色", kind: "status"}, {key: "enabled", label: "状态", kind: "status"}, {key: "lastLoginTime", label: "最后登录", kind: "date"}, {key: "remarks", label: "备注"}]},
  logs: {menuId: "logs", title: "操作日志", subtitle: "追溯库存、订单、财务与权限操作记录。", collection: "logs", columns: [{key: "time", label: "时间", kind: "date"}, {key: "user", label: "操作人"}, {key: "module", label: "模块"}, {key: "type", label: "操作类型", kind: "status"}, {key: "target", label: "目标"}, {key: "beforeVal", label: "变更前"}, {key: "afterVal", label: "变更后"}]},
  profit: {menuId: "finance_reports", title: "销售利润", subtitle: "按销售单据查看销售额、成本、毛利与收款状态。", collection: "salesInvoices", columns: [{key: "invoiceNo", label: "销售单号"}, {key: "date", label: "日期", kind: "date"}, {key: "customerName", label: "客户"}, {key: "totalAmount", label: "销售额", kind: "currency"}, {key: "totalCost", label: "成本", kind: "currency", sensitive: "cost"}, {key: "totalProfit", label: "毛利", kind: "currency", sensitive: "profit"}, {key: "totalCount", label: "数量", kind: "count"}, {key: "outboundStatus", label: "出库状态", kind: "status"}]},
  closing: {menuId: "finance_closing", title: "日结与异常", subtitle: "查看财务流水与待复核事项，日结动作沿用现有后端权限。", collection: "financeLedger", columns: [{key: "time", label: "时间", kind: "date"}, {key: "type", label: "业务类型", kind: "status"}, {key: "amount", label: "金额", kind: "currency"}, {key: "status", label: "复核状态", kind: "status"}, {key: "relatedDocType", label: "单据类型"}, {key: "relatedId", label: "关联单据"}, {key: "operator", label: "操作人"}]},
  returnReconcile: {menuId: "return_reconcile", title: "退货对账", subtitle: "核对销售退货与采购退货的退款、冲销和库存动作。", collection: "returnOrders", columns: [{key: "returnNo", label: "退货单号"}, {key: "type", label: "类型", kind: "status"}, {key: "date", label: "日期", kind: "date"}, {key: "relatedDocNo", label: "关联单据"}, {key: "amount", label: "金额", kind: "currency"}, {key: "settlementMode", label: "结算方式", kind: "status"}, {key: "status", label: "状态", kind: "status"}, {key: "completedAt", label: "完成时间", kind: "date"}]},
  purchaseCommission: {menuId: "purchase_commission", title: "进货提成", subtitle: "查看采购与销售关联的提成计算结果。", collection: "purchaseCommissions", columns: [{key: "id", label: "记录编号"}, {key: "sn", label: "SN"}, {key: "productName", label: "商品"}, {key: "purchaseHandler", label: "采购经办人"}, {key: "costPrice", label: "成本", kind: "currency", sensitive: "cost"}, {key: "grossProfit", label: "毛利", kind: "currency", sensitive: "profit"}, {key: "commissionAmount", label: "提成", kind: "currency", sensitive: "profit"}, {key: "status", label: "状态", kind: "status"}]},
  salesCommission: {menuId: "sales_commission", title: "销售提成", subtitle: "查看已结算销售的提成计算结果；计算规则仍由现有后端负责。", collection: "purchaseCommissions", columns: [{key: "id", label: "记录编号"}, {key: "sn", label: "SN"}, {key: "productName", label: "商品"}, {key: "salesHandler", label: "销售经办人"}, {key: "salePrice", label: "销售价", kind: "currency"}, {key: "grossProfit", label: "毛利", kind: "currency", sensitive: "profit"}, {key: "commissionAmount", label: "提成", kind: "currency", sensitive: "profit"}, {key: "status", label: "状态", kind: "status"}]},
  customerFunds: {menuId: "customer_funds", title: "客户资金", subtitle: "查看客户应收、应付和余额变化。", collection: "customers", columns: [{key: "name", label: "客户"}, {key: "type", label: "类型", kind: "status"}, {key: "receivableBalance", label: "应收余额", kind: "currency"}, {key: "payableBalance", label: "应付余额", kind: "currency"}, {key: "totalAmount", label: "累计交易", kind: "currency"}, {key: "lastDealTime", label: "最近成交", kind: "date"}, {key: "owner", label: "负责人"}]},
} satisfies Record<string, StateCollectionPageProps>;

export type LegacyRouteKey = keyof typeof configs;

export function LegacyRoutePage({configKey}: {configKey: LegacyRouteKey}) {
  return <StateCollectionPage {...configs[configKey]} />;
}
