import {keepPreviousData, useQuery} from "@tanstack/react-query";
import type {ColumnDef} from "@tanstack/react-table";
import {ClipboardList, Filter, RefreshCw, Search} from "lucide-react";
import {useEffect, useState} from "react";
import {Button, Card, Input} from "@/src/components/ui";
import {DashboardSection, ErpDataTable, ErpDetailDrawer, ErpFilterBar, ErpPageError, ErpPageHeader, ErpSettingsPageFrame, ErpStatusBadge, MetricsRegion, type QuickStatusItemData} from "@/src/components/common";
import {ApiError, logsApi, queryKeys, type AuthSession} from "@/src/services/api";
import {createCapabilities, useAuth} from "@/src/app/auth";
import type {AuditLogItem} from "@/src/types/finance-remaining";
import type {LogsFilters} from "@/src/services/api/endpoints/finance-remaining";

function allowed(session: AuthSession | null | undefined) {return Boolean(session?.permissions.allowedMenus.some((id) => id === "all" || id === "logs"));}
export function SettingsLogsPage() {
  const {session, status, error: authError, refresh, logout} = useAuth();
  const canRead = createCapabilities(session).menu("logs") || allowed(session);
  const [filters, setFilters] = useState<LogsFilters>({page: 1, pageSize: 20, keyword: ""});
  const query = useQuery({queryKey: queryKeys.settings.logs(filters), queryFn: ({signal}) => logsApi.list(filters, signal), enabled: Boolean(session && canRead), placeholderData: keepPreviousData, retry: false});
  useEffect(() => {if (query.error instanceof ApiError && query.error.isUnauthorized) logout();}, [logout, query.error]);
  if (status === "loading") return <Card><p className="p-5 text-sm">正在验证操作日志权限…</p></Card>;
  if (status === "error") return <ErpPageError title="无法读取登录状态" description={authError?.message || "请重新登录后继续。"} onRetry={() => void refresh()} />;
  if (!session || !canRead) return <ErpPageError title="当前账号没有操作日志权限" description="服务端不会返回日志记录。" />;
  if (query.error && !query.data) return <ErpPageError title="操作日志加载失败" description={query.error.message} onRetry={() => void query.refetch()} />;
  return <SettingsLogsContent filters={filters} setFilters={setFilters} query={query} />;
}
function SettingsLogsContent({filters, setFilters, query}: {filters: LogsFilters; setFilters: (value: LogsFilters) => void; query: ReturnType<typeof useQuery<Awaited<ReturnType<typeof logsApi.list>>>>}) {
  const [detail, setDetail] = useState<AuditLogItem | null>(null); const data = query.data; const items = data?.items || []; const meta = data?.meta; const columns: ColumnDef<AuditLogItem, unknown>[] = [{accessorKey: "time", header: "时间", size: 150, cell: ({row}) => <span className="font-mono text-xs">{row.original.time}</span>}, {accessorKey: "user", header: "操作人", size: 120}, {accessorKey: "module", header: "模块", size: 120}, {accessorKey: "type", header: "动作", size: 120, cell: ({row}) => <ErpStatusBadge label={row.original.type} tone="info" />}, {accessorKey: "target", header: "目标", size: 220}, {id: "action", header: "操作", size: 80, cell: ({row}) => <Button type="button" size="sm" variant="ghost" onClick={(event) => {event.stopPropagation(); setDetail(row.original);}}>详情</Button>}]; const active = Boolean(filters.keyword); const quickStatus: QuickStatusItemData[] = [{icon: <ClipboardList className="h-4 w-4" />, label: "日志记录", value: `${meta?.total || 0} 条`, description: "当前筛选结果", status: "info"}, {icon: <ClipboardList className="h-4 w-4" />, label: "当前页", value: `${items.length} 条`, description: "保留原始变更审计", status: "neutral"}]; const updateKeyword = (keyword: string) => setFilters({...filters, keyword, page: 1});
  return <ErpSettingsPageFrame><ErpPageHeader title="操作日志" subtitle="查看谁在什么时间对哪个业务对象执行了什么操作。" quickStatus={quickStatus} actions={<Button type="button" size="sm" variant="secondary" onClick={() => void query.refetch()} disabled={query.isFetching}><RefreshCw className={query.isFetching ? "h-4 w-4 animate-spin" : "h-4 w-4"} />刷新</Button>} /><MetricsRegion><Metric label="日志总数" value={`${meta?.total || 0} 条`} detail="服务端真实总数" /><Metric label="当前页" value={`${items.length} 条`} detail={`第 ${meta?.page || filters.page} 页`} /><Metric label="筛选状态" value={active ? "已筛选" : "全部"} detail="关键字过滤" /></MetricsRegion><ErpFilterBar actions={<Button type="button" size="sm" variant="ghost" onClick={() => setFilters({page: 1, pageSize: filters.pageSize, keyword: ""})} disabled={!active}><Filter className="h-4 w-4" />重置筛选</Button>}><div className="relative min-w-64 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--erp-color-text-muted)]" /><Input className="pl-9" value={filters.keyword} onChange={(event) => updateKeyword(event.target.value)} placeholder="操作人、模块、目标或动作" aria-label="搜索操作日志" /></div></ErpFilterBar><DashboardSection title="审计记录" description="日志接口使用服务端分页；删除日志等高风险动作仍由现有权限与后台流程负责。"><ErpDataTable columns={columns} data={items} getRowId={(row) => row.id} loading={query.isPending} fetching={query.isFetching} error={query.error as Error | null} errorTitle="操作日志刷新失败" emptyTitle="暂无操作日志" emptyDescription={active ? "当前关键字没有匹配记录。" : "系统尚未记录可见操作。"} onRetry={() => void query.refetch()} onRowClick={setDetail} page={meta?.page || filters.page} pageSize={meta?.pageSize || filters.pageSize} total={meta?.total || 0} onPageChange={(page) => setFilters({...filters, page})} onPageSizeChange={(pageSize) => setFilters({...filters, page: 1, pageSize})} stickyHeader density="compact" /></DashboardSection><ErpDetailDrawer open={Boolean(detail)} onOpenChange={(open) => {if (!open) setDetail(null);}} title="操作日志详情" description={detail ? `${detail.module} · ${detail.type}` : undefined}>{detail && <div className="space-y-4"><div className="grid grid-cols-2 gap-3"><Fact label="时间" value={detail.time} /><Fact label="操作人" value={detail.user} /><Fact label="模块" value={detail.module} /><Fact label="动作" value={detail.type} /><Fact label="目标" value={detail.target} /></div><DashboardSection title="变更前后"><div className="space-y-3"><pre className="erp-scrollbar max-h-48 overflow-auto rounded-[var(--erp-radius-md)] bg-[var(--erp-color-surface-muted)] p-3 text-xs whitespace-pre-wrap">变更前：{detail.beforeVal || "—"}</pre><pre className="erp-scrollbar max-h-48 overflow-auto rounded-[var(--erp-radius-md)] bg-[var(--erp-color-surface-muted)] p-3 text-xs whitespace-pre-wrap">变更后：{detail.afterVal || "—"}</pre></div></DashboardSection></div>}</ErpDetailDrawer></ErpSettingsPageFrame>;
}
function Metric({label, value, detail}: {label: string; value: string; detail: string}) {return <Card><div className="p-4"><p className="text-xs text-[var(--erp-color-text-secondary)]">{label}</p><p className="mt-2 font-mono text-xl font-bold">{value}</p><p className="mt-1 text-[11px] text-[var(--erp-color-text-muted)]">{detail}</p></div></Card>;}
function Fact({label, value}: {label: string; value: string}) {return <div className="rounded-[var(--erp-radius-md)] border border-[var(--erp-color-border)] p-3"><p className="text-[11px] text-[var(--erp-color-text-muted)]">{label}</p><p className="mt-1 truncate text-sm font-semibold">{value}</p></div>;}
