import {RefreshCw} from "lucide-react";
import type {Dispatch, SetStateAction} from "react";
import {Button, Dialog, Input, Textarea} from "@/src/components/ui";
import {formatCurrency} from "@/src/lib/format";
import type {SalesReturnListItem} from "@/src/types/returns";

export type ReturnEditDraft = Pick<SalesReturnListItem, "handler" | "reason" | "remarks">;

export function ReturnEditDialog({target, draft, pending, error, onClose, onDraftChange, onConfirm}: {target: SalesReturnListItem | null; draft: ReturnEditDraft; pending: boolean; error: string; onClose: () => void; onDraftChange: Dispatch<SetStateAction<ReturnEditDraft>>; onConfirm: () => void}) {
  return <Dialog.Root open={Boolean(target)} onOpenChange={(open) => {if (!open) onClose();}}><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 erp-modal-layer bg-[var(--erp-color-backdrop)] backdrop-blur-sm" /><Dialog.Viewport className="fixed inset-0 erp-modal-layer flex items-center justify-center p-4"><Dialog.Popup className="w-full max-w-lg rounded-[var(--erp-radius-xl)] border border-[var(--erp-color-border)] bg-[var(--erp-color-surface)] p-5 shadow-[var(--erp-shadow-popover)]"><Dialog.Title className="text-base font-bold">编辑退货单资料</Dialog.Title><Dialog.Description className="mt-2 text-sm text-[var(--erp-color-text-secondary)]">{target ? `${target.returnNo} · 只修改经办人、退货原因和备注，不改变退款、库存或金额。` : ""}</Dialog.Description><div className="mt-5 space-y-4"><label className="block text-sm font-semibold">经办人<Input className="mt-2" value={draft.handler} onChange={(event) => onDraftChange((current) => ({...current, handler: event.target.value}))} /></label><label className="block text-sm font-semibold">退货原因<Textarea className="mt-2 min-h-20" value={draft.reason} onChange={(event) => onDraftChange((current) => ({...current, reason: event.target.value}))} /></label><label className="block text-sm font-semibold">备注<Textarea className="mt-2 min-h-24" value={draft.remarks} onChange={(event) => onDraftChange((current) => ({...current, remarks: event.target.value}))} /></label>{error && <p role="alert" className="rounded-[var(--erp-radius-md)] bg-[var(--erp-color-danger-soft)] p-3 text-xs text-[var(--erp-color-danger)]">{error}</p>}</div><div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" disabled={pending} onClick={onClose}>取消</Button><Button type="button" variant="primary" disabled={pending || !draft.handler.trim() || !draft.reason.trim()} onClick={onConfirm}>{pending ? <RefreshCw className="h-4 w-4 animate-spin" /> : "保存修改"}</Button></div></Dialog.Popup></Dialog.Viewport></Dialog.Portal></Dialog.Root>;
}

export function DeleteReturnDialog({target, pending, error, onClose, onConfirm}: {target: SalesReturnListItem | null; pending: boolean; error: string; onClose: () => void; onConfirm: () => void}) {
  const completed = target?.status === "已完成";
  return <Dialog.Root open={Boolean(target)} onOpenChange={(open) => {if (!open && !pending) onClose();}}><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 erp-modal-layer bg-[var(--erp-color-backdrop)] backdrop-blur-sm" /><Dialog.Viewport className="fixed inset-0 erp-modal-layer flex items-center justify-center p-4"><Dialog.Popup className="w-full max-w-lg rounded-[var(--erp-radius-xl)] border border-[var(--erp-color-border)] bg-[var(--erp-color-surface)] p-5 shadow-[var(--erp-shadow-popover)]"><Dialog.Title className="text-base font-bold">{completed ? "删除并冲销退货" : "删除退货单"}</Dialog.Title><Dialog.Description className="mt-2 text-sm text-[var(--erp-color-text-secondary)]">{completed ? "服务端会同步恢复原单据、库存状态、账户流水和供应商账款；只有服务端校验通过才会执行。" : "删除待处理退货单后不会触发退款或库存完成动作，操作仍由服务端校验。"}</Dialog.Description>{target && <div className={`mt-4 rounded-[var(--erp-radius-md)] p-4 ${completed ? "bg-[var(--erp-color-danger-soft)] text-[var(--erp-color-danger)]" : "bg-[var(--erp-color-surface-muted)]"}`}><p className="font-mono text-xs font-bold">{target.returnNo}</p><p className="mt-2 text-sm font-semibold">{target.productName} · {formatCurrency(target.amount)}</p><p className="mt-1 text-xs">{target.settlementMode || "未记录结算方式"} · {target.inventoryAction || "未记录库存处理"}</p></div>}{error && <p role="alert" className="mt-4 rounded-[var(--erp-radius-md)] bg-[var(--erp-color-danger-soft)] p-3 text-xs text-[var(--erp-color-danger)]">{error}</p>}<div className="mt-5 flex justify-end gap-2"><Button type="button" variant="secondary" disabled={pending} onClick={onClose}>取消</Button><Button type="button" variant="danger" disabled={pending} onClick={onConfirm}>{pending ? <RefreshCw className="h-4 w-4 animate-spin" /> : completed ? "确认删除并冲销" : "确认删除"}</Button></div></Dialog.Popup></Dialog.Viewport></Dialog.Portal></Dialog.Root>;
}

export function csvCell(value: string | number) {
  const text = String(value ?? "");
  return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}
