/**
 * The route tree and the keep-alive workspace both need the same page module
 * loaders. Keeping the imports here prevents a newly-added page from being
 * registered in one lazy-loading path but not the other.
 */
export const pageLoaders = {
  dashboard: () => import("@/src/features/dashboard/pages/DashboardPage"),
  inventory: () => import("@/src/features/inventory/pages/InventoryListPage"),
  salesList: () => import("@/src/features/sales/pages/SalesListPage"),
  salesNew: () => import("@/src/features/sales/pages/NewSalesOrderPage"),
  salesDetail: () => import("@/src/features/sales/pages/SalesDetailPage"),
  salesEdit: () => import("@/src/features/sales/pages/SalesEditPage"),
  salesOutbound: () => import("@/src/features/sales/pages/SalesOutboundPage"),
  aiInsights: () => import("@/src/features/ai/pages/AiInsightsPage"),
  quotes: () => import("@/src/features/quotes/pages/MarketQuotesPage"),
  products: () => import("@/src/features/products/pages/ProductLibraryPage"),
  assembly: () => import("@/src/features/assembly/pages/AssemblyWorkspacePage"),
  purchaseList: () => import("@/src/features/purchase/pages/PurchaseListPage"),
  purchaseNew: () => import("@/src/features/purchase/pages/NewPurchaseOrderPage"),
  purchaseDetail: () => import("@/src/features/purchase/pages/PurchaseDetailPage"),
  purchaseEdit: () => import("@/src/features/purchase/pages/PurchaseEditPage"),
  inspections: () => import("@/src/features/inspections/pages/InspectionWorkspacePage"),
  purchaseReturns: () => import("@/src/features/returns/pages/PurchaseReturnListPage"),
  purchaseReturnsNew: () => import("@/src/features/returns/pages/NewPurchaseReturnPage"),
  salesReturns: () => import("@/src/features/returns/pages/SalesReturnListPage"),
  salesReturnsNew: () => import("@/src/features/returns/pages/NewSalesReturnPage"),
  crm: () => import("@/src/features/crm/pages/CrmWorkspacePage"),
  crmCustomerNew: () => import("@/src/features/crm/pages/NewCustomerLeadPage"),
  customers: () => import("@/src/features/customers/pages/CustomerDirectoryPage"),
  vendors: () => import("@/src/features/vendors/pages/VendorDirectoryPage"),
  orderPool: () => import("@/src/features/order-pool/pages/OrderPoolPage"),
  aftersales: () => import("@/src/features/aftersales/pages/AftersalesWorkspacePage"),
  financeDashboard: () => import("@/src/features/finance/pages/FinanceDashboardPage"),
  financeAccounts: () => import("@/src/features/finance/pages/FinanceAccountsPage"),
  financeLedger: () => import("@/src/features/finance/pages/FinanceLedgerPage"),
  financeIncome: () => import("@/src/features/finance/pages/FinanceIncomePage"),
  financeExpense: () => import("@/src/features/finance/pages/FinanceExpensePage"),
  financeTransfers: () => import("@/src/features/finance/pages/FinanceTransfersPage"),
  financeProfit: () => import("@/src/features/finance/pages/FinanceProfitPage"),
  financeClosing: () => import("@/src/features/finance/pages/FinanceClosingPage"),
  financeReturnReconcile: () => import("@/src/features/finance/pages/FinanceReturnReconcilePage"),
  financeCommission: () => import("@/src/features/finance/pages/FinanceCommissionPage"),
  financeCustomerFunds: () => import("@/src/features/finance/pages/FinanceCustomerFundsPage"),
  settingsUsers: () => import("@/src/features/settings/pages/SettingsUsersPage"),
  settingsLogs: () => import("@/src/features/settings/pages/SettingsLogsPage"),
  backup: () => import("@/src/features/settings/pages/BackupPage"),
  designSystem: () => import("@/src/features/design-system/pages/DesignSystemPage"),
} as const;
