import type {FinanceDashboardResponseDto} from "../dto/finance.dto";
import type {FinanceDashboardAccess, FinanceDashboardDataset, FinanceDashboardView, FinanceDateRange, FinanceException, FinanceFlowDay, FinanceHealthRisk} from "@/src/types/finance";
import {addDateDays} from "@/src/lib/dateRangePickerUtils";

function record(value: unknown): Record<string, unknown> {return value && typeof value === "object" ? value as Record<string, unknown> : {};}
function collection(value: unknown) {return Array.isArray(value) ? value : [];}
function text(value: unknown, fallback = "") {return typeof value === "string" ? value : value === null || value === undefined ? fallback : String(value);}
function optionalText(value: unknown) {const result = text(value).trim(); return result || undefined;}
function numberValue(value: unknown) {const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0;}
function optionalNumber(value: unknown) {if (value === null || value === undefined || value === "") return undefined; const parsed = Number(value); return Number.isFinite(parsed) ? parsed : undefined;}
const datePart = (value: unknown) => text(value).slice(0, 10);

export function adaptFinanceDashboardDataset(response: FinanceDashboardResponseDto, access: FinanceDashboardAccess): FinanceDashboardDataset {
  const state = record(response.data);
  const accounts = access.canViewAccounts ? collection(state.settlementAccounts).map(record).map((item) => ({id: text(item.id), name: text(item.name, "未命名账户"), type: text(item.type), balance: numberValue(item.balance), availableBalance: numberValue(item.availableBalance ?? item.balance), enabled: item.enabled !== false, actualBalance: optionalNumber(item.actualBalance)})).filter((item) => Boolean(item.id)) : [];
  const flows = access.canViewSettlementLedger ? collection(state.settlementLedger).map(record).map((item) => ({id: text(item.id), time: text(item.time), accountName: text(item.accountName), businessType: text(item.businessType, "未分类资金变动"), income: Math.max(0, numberValue(item.incomeAmount)), expense: Math.max(0, numberValue(item.expenseAmount)), net: numberValue(item.changeAmount) || Math.max(0, numberValue(item.incomeAmount)) - Math.max(0, numberValue(item.expenseAmount)), party: optionalText(item.customerName || item.supplierName), relatedDocNo: optionalText(item.relatedDocNo)})).filter((item) => Boolean(item.id)) : [];
  const reviewStatuses = collection(state.financeLedger).map(record).map((item) => text(item.status));
  const sales = collection(state.salesInvoices).map(record).map((item) => ({date: datePart(item.date), outboundDate: optionalText(item.outboundTime)?.slice(0, 10), outbound: text(item.outboundStatus) === "已出库", ...(access.showCost ? {totalCost: Math.max(0, numberValue(item.totalCost))} : {}), ...(access.showProfit ? {totalProfit: numberValue(item.totalProfit)} : {}), unpaid: Math.max(0, numberValue(item.unpaidAmount)), refunded: text(item.paymentStatus) === "已退款"}));
  const purchases = collection(state.purchaseInvoices).map(record).map((item) => ({date: datePart(item.date), ...(access.showCost ? {totalCost: Math.max(0, numberValue(item.totalCost))} : {}), unpaid: Math.max(0, numberValue(item.unpaidAmount))}));
  const returns = access.canViewReturns ? collection(state.returnOrders).map(record).map((item) => {const saleSnapshot = record(item.sourceSalesItemSnapshot); const purchaseSnapshot = record(item.sourcePurchaseItemSnapshot); return {date: datePart(item.date), status: text(item.status), type: text(item.type), amount: Math.max(0, numberValue(item.amount)), ...(access.showCost ? {salesCost: Math.max(0, numberValue(saleSnapshot.costPrice)), purchaseCost: Math.max(0, numberValue(purchaseSnapshot.buyPrice))} : {})};}) : [];
  const inventory = collection(state.inventory).map(record).map((item) => ({status: text(item.status), ...(access.showCost ? {cost: Math.max(0, numberValue(item.costPrice))} : {}), entryDate: datePart(item.entryTime), salesDate: optionalText(item.salesTime)?.slice(0, 10)}));
  return {accounts, flows, reviewStatuses, sales, purchases, returns, inventory, access, source: "state-snapshot"};
}

export function buildFinanceDashboard(dataset: FinanceDashboardDataset, range: FinanceDateRange, today: string): FinanceDashboardView {
  const yesterday = addDays(today, -1); const todayRows = flowsOn(dataset, today); const yesterdayRows = flowsOn(dataset, yesterday);
  const activeAccounts = dataset.accounts.filter((item) => item.enabled); const availableCash = dataset.access.canViewAccounts ? activeAccounts.reduce((sum, item) => sum + item.availableBalance, 0) : undefined; const bookBalance = dataset.access.canViewAccounts ? activeAccounts.reduce((sum, item) => sum + item.balance, 0) : undefined;
  const receivable = dataset.sales.filter((item) => item.unpaid > 0 && !item.refunded).reduce((sum, item) => sum + item.unpaid, 0); const payable = dataset.purchases.filter((item) => item.unpaid > 0).reduce((sum, item) => sum + item.unpaid, 0); const unreviewed = dataset.reviewStatuses.filter(isPendingReview).length; const accountDifferenceRows = dataset.access.canViewAccounts ? activeAccounts.filter((item) => item.actualBalance !== undefined && Math.abs(item.actualBalance - item.balance) > 0.009) : []; const accountDifferences = dataset.access.canViewAccounts ? accountDifferenceRows.length : undefined; const accountDifferenceAmount = dataset.access.canViewAccounts ? accountDifferenceRows.reduce((sum, item) => sum + Math.abs((item.actualBalance || 0) - item.balance), 0) : undefined; const accountBalanceBase = activeAccounts.reduce((sum, item) => sum + Math.abs(item.balance), 0); const pendingReturnRows = dataset.access.canViewReturns ? dataset.returns.filter((item) => item.status === "待处理") : []; const pendingReturns = dataset.access.canViewReturns ? pendingReturnRows.length : undefined; const pendingReturnAmount = dataset.access.canViewReturns ? pendingReturnRows.reduce((sum, item) => sum + (item.amount || 0), 0) : undefined;
  const trend = dateRows(range).map((date): FinanceFlowDay => {const rows = flowsOn(dataset, date); const income = rows.reduce((sum, item) => sum + item.income, 0); const expense = rows.reduce((sum, item) => sum + item.expense, 0); return {date, label: date.slice(5), income, expense, net: income - expense};});
  const currentPeriod = sumFlows(trend); const periodDays = Math.max(1, trend.length); const previousRange = {startDate: addDays(range.startDate, -periodDays), endDate: addDays(range.startDate, -1)}; const previousPeriod = sumFlows(dateRows(previousRange).map((date) => {const rows = flowsOn(dataset, date); const income = rows.reduce((sum, item) => sum + item.income, 0); const expense = rows.reduce((sum, item) => sum + item.expense, 0); return {date, label: date.slice(5), income, expense, net: income - expense};}));
  const grossProfit = dataset.access.showProfit ? dataset.sales.filter((item) => item.date === today).reduce((sum, item) => sum + (item.totalProfit || 0), 0) : undefined;
  const exceptions: FinanceException[] = [];
  if (availableCash !== undefined && availableCash <= 0) exceptions.push({id: "cash", title: availableCash < 0 ? "可用资金不足" : "暂无可用资金", detail: `当前可用资金 ${formatMoney(availableCash)}`, tone: "danger", route: "/finance/accounts"});
  if (unreviewed) exceptions.push({id: "unreviewed", title: "待复核资金流水", detail: `${unreviewed} 笔尚未完成核对`, tone: "danger", route: "/finance/closing"});
  if (accountDifferences) exceptions.push({id: "accounts", title: "账户实盘存在差额", detail: `${accountDifferences} 个账户有差额，共 ${formatMoney(accountDifferenceAmount || 0)}`, tone: "warning", route: "/finance/closing"});
  if (pendingReturns) exceptions.push({id: "returns", title: "退货待完成结算", detail: `${pendingReturns} 笔需要确认退款或冲销，共 ${formatMoney(pendingReturnAmount || 0)}`, tone: "warning", route: "/finance/return-reconcile"});
  if (receivable) exceptions.push({id: "receivable", title: "客户应收款待跟进", detail: `待收 ${formatMoney(receivable)}`, tone: "danger", route: "/finance/closing"});
  if (payable) exceptions.push({id: "payable", title: "供应商应付款待安排", detail: `待付 ${formatMoney(payable)}`, tone: "warning", route: "/finance/closing"});
  const healthScore = availableCash === undefined || !dataset.access.canViewSettlementLedger ? undefined : calculateHealth({availableCash, periodExpense: currentPeriod.expense, periodDays, unreviewed, accountDifferenceAmount: accountDifferenceAmount || 0, accountBalanceBase, pendingReturnAmount: pendingReturnAmount || 0, pendingReturns: pendingReturns || 0, receivable, payable});
  const healthRisk = healthScore === undefined || availableCash === undefined ? undefined : healthRiskFor(healthScore, availableCash);
  return {today, availableCash, bookBalance, todayIncome: dataset.access.canViewSettlementLedger ? todayRows.reduce((sum, item) => sum + item.income, 0) : undefined, todayExpense: dataset.access.canViewSettlementLedger ? todayRows.reduce((sum, item) => sum + item.expense, 0) : undefined, yesterdayIncome: dataset.access.canViewSettlementLedger ? yesterdayRows.reduce((sum, item) => sum + item.income, 0) : undefined, yesterdayExpense: dataset.access.canViewSettlementLedger ? yesterdayRows.reduce((sum, item) => sum + item.expense, 0) : undefined, grossProfit, receivable, payable, unreviewed, accountDifferences, accountDifferenceAmount, pendingReturns, pendingReturnAmount, trend, currentPeriod, previousPeriod, healthScore, healthRisk, exceptions, recentEvents: [...dataset.flows].sort((a, b) => b.time.localeCompare(a.time) || b.id.localeCompare(a.id)).slice(0, 4), turnover: dataset.access.showCost ? calculateTurnover(dataset, range, receivable, payable) : undefined};
}

function calculateTurnover(dataset: FinanceDashboardDataset, range: FinanceDateRange, receivable: number, payable: number) {
  const terminal = new Set(["已售出", "已退货", "已报废"]); const endingInventoryCost = dataset.inventory.filter((item) => !terminal.has(item.status)).reduce((sum, item) => sum + (item.cost || 0), 0); const inventorySoldCost = dataset.inventory.filter((item) => item.status === "已售出" && inRange(item.salesDate, range)).reduce((sum, item) => sum + (item.cost || 0), 0); const invoiceSoldCost = dataset.sales.filter((item) => item.outbound && inRange(item.outboundDate || item.date, range)).reduce((sum, item) => sum + (item.totalCost || 0), 0); const soldCost = inventorySoldCost > 0 ? inventorySoldCost : invoiceSoldCost; const periodInboundCost = dataset.inventory.filter((item) => inRange(item.entryDate, range)).reduce((sum, item) => sum + (item.cost || 0), 0); const legacyPurchaseCost = dataset.purchases.filter((item) => inRange(item.date, range)).reduce((sum, item) => sum + (item.totalCost || 0), 0); const inboundCost = periodInboundCost > 0 ? periodInboundCost : legacyPurchaseCost; const salesReturnCost = dataset.returns.filter((item) => item.status === "已完成" && item.type === "销售退货" && inRange(item.date, range)).reduce((sum, item) => sum + (item.salesCost || 0), 0); const purchaseReturnCost = dataset.returns.filter((item) => item.status === "已完成" && item.type === "进货退货" && inRange(item.date, range)).reduce((sum, item) => sum + (item.purchaseCost || 0), 0); const openingInventory = Math.max(0, endingInventoryCost - inboundCost - salesReturnCost + soldCost + purchaseReturnCost); const endingCapital = Math.max(0, endingInventoryCost + receivable - payable); const openingCapital = Math.max(0, openingInventory + receivable - payable); const averageCapitalOccupied = (openingCapital + endingCapital) / 2; const periodDays = dateRows(range).length; const turnover = averageCapitalOccupied > 0 && soldCost > 0 ? soldCost / averageCapitalOccupied : null; return {turnover, turnoverDays: turnover ? periodDays / turnover : null, averageCapitalOccupied, periodDays};
}

function flowsOn(dataset: FinanceDashboardDataset, date: string) {return dataset.flows.filter((item) => item.time.startsWith(date));}
function isPendingReview(value: string) {return ["待审核", "未复核", "待复核"].includes(value);}
function inRange(value: string | undefined, range: FinanceDateRange) {return Boolean(value && value >= range.startDate && value <= range.endDate);}
function addDays(value: string, days: number) {return addDateDays(value, days);}
function dateRows(range: FinanceDateRange) {const rows: string[] = []; for (let date = range.startDate, guard = 0; date <= range.endDate && guard < 366; date = addDays(date, 1), guard += 1) rows.push(date); return rows.length ? rows : [range.endDate];}
function sumFlows(rows: FinanceFlowDay[]) {return rows.reduce((total, item) => ({income: total.income + item.income, expense: total.expense + item.expense, net: total.net + item.net}), {income: 0, expense: 0, net: 0});}
function clamp(value: number, min: number, max: number) {return Math.min(max, Math.max(min, value));}
function calculateHealth(input: {availableCash: number; periodExpense: number; periodDays: number; unreviewed: number; accountDifferenceAmount: number; accountBalanceBase: number; pendingReturnAmount: number; pendingReturns: number; receivable: number; payable: number}) {
  const dailyExpense = input.periodExpense / Math.max(1, input.periodDays);
  const runwayDays = dailyExpense > 0 ? input.availableCash / dailyExpense : input.availableCash > 0 ? 30 : 0;
  const cashRisk = input.availableCash <= 0 ? 45 : runwayDays < 3 ? 32 : runwayDays < 7 ? 20 : runwayDays < 14 ? 10 : 0;
  const receivableRisk = clamp(input.receivable / Math.max(input.availableCash + input.receivable, 1) * 20, 0, 20);
  const payableRisk = clamp(input.payable / Math.max(input.availableCash + input.payable, 1) * 20, 0, 20);
  const reviewRisk = Math.min(12, input.unreviewed * 3);
  const accountRisk = input.accountDifferenceAmount > 0 ? clamp(input.accountDifferenceAmount / Math.max(input.accountBalanceBase, 1) * 18, 2, 18) : 0;
  const returnRisk = input.pendingReturns > 0 ? clamp(Math.max(2, input.pendingReturnAmount / Math.max(input.availableCash + input.pendingReturnAmount, 1) * 10), 0, 10) : 0;
  return Math.round(clamp(100 - cashRisk - receivableRisk - payableRisk - reviewRisk - accountRisk - returnRisk, 0, 100));
}
function healthRiskFor(score: number, availableCash: number): FinanceHealthRisk {if (availableCash <= 0 || score < 60) return "high"; if (score < 85) return "attention"; return "low";}
function formatMoney(value: number) {return `¥${Number(value || 0).toLocaleString("zh-CN", {maximumFractionDigits: 2})}`;}
